### ISSUE TITLE
NUTS adapatation samples appear in full chain

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#635]
It looks like the samples from the `NUTS` adaptation phase are being included in the full chain. Is this expected behavior? If not, we need some kind of infrastructure in place to separate out the adaptation samples from the chains so that parameter estimates are more appropriate.

Let me know if this needs to be moved over to [MCMCChains](https://github.com/TuringLang/MCMCChain.jl).

**Comment by goedman** [comment]
The links are no longer correct.

**Comment by yebai** [comment]
@kai @cpfiffer Is this fixed by recent changes in AHMC and MCMCChains?

**Comment by cpfiffer** [comment]
No, MCMCChains still does not have any internals to catch adaptation samples. I'm wondering if we should fix this on the Turing side by defaulting to only return the post-warmup samples, and discarding the adaptation samples unless the user specifically requests them (using a keyword like `NUTS(. . . , keep_warmup=true)` or something). Does that seem reasonable? Is there any reason to keep the warmup samples around if most people just get rid of them?

**Comment by robsmith11** [comment]
As a beginner attempting to reproduce the resuts of a simple linear model from Stan, I was surprised to the see the warmup samples included in the summary stats.  I expected them to have been removed.

**Comment by yebai** [comment]
Excluding warmup samples from chains sounds reasonable. In the longer term, we might want an argument for the `sample` interface (https://github.com/TuringLang/Turing.jl/issues/746) to decide to retain/discard warmup samples.

**Comment by cpfiffer** [comment]
I've opened up a PR Turing-side to fix this: https://github.com/TuringLang/Turing.jl/pull/784
